### PR TITLE
Add a tips to save and exit.

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by umpirsky** [comment]
@lyrixx Thinking what is the best way to do that. Any suggestion?

**Comment by lyrixx** [comment]
To do what ?

**Comment by umpirsky** [comment]
@lyrixx To present this on website.

**Comment by lyrixx** [comment]
Ah. I don't know. I let you decide ;)

**Comment by umpirsky** [comment]
:)

**Comment by umpirsky** [comment]
Added http://exitvi.io/save-and-quit, thanks. :)

**Pull request closed without merging**
